In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [3]:
nba_df = pd.read_csv("Datasets/all_seasons.csv")
nba_df.head()

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,...,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,...,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,...,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,...,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,...,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97

In [5]:
nba_df1 = nba_df.drop(columns = ["team_abbreviation", "player_height", "player_weight", "college", "draft_year", "draft_round"])

In [8]:
nba_df2 = nba_df1.drop(columns = ["Unnamed: 0", "draft_number", "oreb_pct", "dreb_pct", "ast_pct"])
nba_df2

,player_name,age,country,gp,pts,reb,ast,net_rating,usg_pct,ts_pct,season
0,Randy Livingston,22.0,USA,64,3.9,1.5,2.4,0.3,0.169,0.487,1996-97
1,Gaylon Nickerson,28.0,USA,4,3.8,1.3,0.3,8.9,0.174,0.497,1996-97
2,George Lynch,26.0,USA,41,8.3,6.4,1.9,-8.2,0.175,0.512,1996-97
3,George McCloud,30.0,USA,64,10.2,2.8,1.7,-2.7,0.206,0.527,1996-97
4,George Zidek,23.0,USA,52,2.8,1.7,0.3,-14.1,0.195,0.500,1996-97
...,...,...,...,...,...,...,...,...,...,...,...
12839,Joel Embiid,29.0,Cameroon,66,33.1,10.2,4.2,8.8,0.370,0.655,2022-23
12840,John Butler Jr.,20.0,USA,19,2.4,0.9,0.6,-16.1,0.102,0.411,2022-23
12841,John Collins,25.0,USA,71,13.1,6.5,1.2,-0.2,0.168,0.593,2022-23
12842,Jericho Sims,24.0,USA,52,3.4,4.7,0.5,-6.7,0.074,0.780,2022-23
12843,JaMychal Green,33.0,USA,57,6.4,3.6,0.9,-8.2,0.169,0.650,2022-23

In [10]:
nba_df2 = nba_df2[nba_df2["pts"] > 20]

In [11]:
nba_df2

,player_name,age,country,gp,pts,reb,ast,net_rating,usg_pct,ts_pct,season
7,Glen Rice,30.0,USA,79,26.8,4.0,2.0,3.2,0.272,0.605,1996-97
8,Glenn Robinson,24.0,USA,80,21.1,6.3,3.1,-2.9,0.278,0.528,1996-97
9,Grant Hill,24.0,USA,80,21.4,9.0,7.3,6.9,0.283,0.556,1996-97
18,Hakeem Olajuwon,34.0,Nigeria,78,23.2,9.2,3.0,6.5,0.308,0.558,1996-97
22,Gary Payton,28.0,USA,82,21.8,4.6,7.1,10.3,0.264,0.545,1996-97
...,...,...,...,...,...,...,...,...,...,...,...
12822,Jaylen Brown,26.0,USA,67,26.6,6.9,3.5,5.4,0.307,0.581,2022-23
12825,Jayson Tatum,25.0,USA,74,30.1,8.8,4.6,8.5,0.319,0.607,2022-23
12829,Jerami Grant,29.0,USA,63,20.5,4.5,2.4,-1.2,0.227,0.606,2022-23
12834,Jimmy Butler,33.0,USA,64,22.9,5.9,5.3,1.2,0.248,0.647,2022-23
12839,Joel Embiid,29.0,Cameroon,66,33.1,10.2,4.2,8.8,0.370,0.655,2022-23